Repository sebadg34/LSA-Capstone-App, pull requests merged in 2023-05, with the labels that each got.

#28 feat: agregado agregar/quitar/visualizar cotizaciones y cambios estil…
  src/components/admPersonal/modal_detallesPersonal.vue
  src/components/admSolicitante/modal_agregarCotizacion.vue
  src/components/admSolicitante/modal_detallesSolicitante.vue
  src/components/admSolicitante/modal_editarSolicitante.vue
  src/components/admSolicitante/modal_listadoCotizaciones.vue
  src/helpers/api-services/Empresa.service.js
  src/helpers/api-services/Solicitante.service.js
  src/views/USU002_admEmpresa.vue
  src/views/USU003_admSolicitante.vue
Labels: enhancement

#29 feat:Agregados modals y corregidos fixes declarados en los requisitos
  src/components/recepcionMuestra/modal_datosMuestra.vue
  src/components/recepcionMuestra/modal_datosRecepcion.vue
  src/components/recepcionMuestra/modal_datosTransportista.vue
  src/router/index.js
  src/views/MUS001.vue
Labels: bug, enhancement

#32 Feat & fix: arreglos menores a vistas involucradas con el formulario principal y agregados nuevos modals y funciones
  src/components/admMuestras/modal_analistaDesignado.vue
  src/components/admMuestras/modal_detallesMuestra.vue
  src/components/admMuestras/modal_rehacerAnalisis.vue
  src/components/recepcionMuestra/modal_datosMuestra.vue
  src/components/recepcionMuestra/modal_datosRecepcion.vue
  src/components/recepcionMuestra/modal_datosTransportista.vue
  src/helpers/api-services/Muestra.Service.js
  src/views/MUS001.vue
  src/views/MUS002-IngMuesLab.vue
  src/views/MUS004-vistaSuperv-Jefe.vue
  src/views/ModalObservaciones.vue
Labels: bug, enhancement

#33 fix: Fixes añadidos a mus 001 y 002
  src/components/recepcionMuestra/modal_datosRecepcion.vue
  src/helpers/api-services/Muestra.Service.js
  src/views/MUS001.vue
  src/views/MUS002-IngMuesLab.vue
  src/views/ModalObservaciones.vue
Labels: bug
